version: "3.8"

services:
  app:
    image: harshfabninjas/face_finder_app:latest
    depends_on:
      - mysql
    networks:
      - laravel-net

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net

  scheduler-and-queue:
    image: harshfabninjas/face_finder_app:latest
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf", "-n"]
    depends_on:
      - app
      - face-recognition-apis
    networks:
      - laravel-net

  face-recognition-apis:
    image: harshfabninjas/face_recognition_apis:latest
    ports:
      - "8005:8005"
    networks:
      - laravel-net
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/docs"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  db_data:

networks:
  laravel-net:
    driver: bridge
