resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    client_max_body_size 1024M; # Prevent gateway timeout on large uploads
    fastcgi_read_timeout 600s;
    proxy_read_timeout 600s;
    send_timeout 600s;

    index index.php index.html;

    location ^~ /build/ {
        proxy_pass http://facefinder_face_finder_app:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_next_upstream_tries 3;
    }

    location /favicon.ico {
        proxy_pass http://facefinder_face_finder_app:9000;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        set $php_upstream facefinder_face_finder_app:9000;
        fastcgi_pass $php_upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_next_upstream error timeout invalid_header http_500 http_503;
        fastcgi_next_upstream_tries 3;
        fastcgi_next_upstream_timeout 10s;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
