[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm
directory=/var/www
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:queue_%(process_num)s]
command=php /var/www/artisan queue:work --queue=high --sleep=3 --tries=3 --timeout=600
directory=/var/www
autostart=true
autorestart=true
numprocs=3
process_name=%(program_name)s_%(process_num)s
startsecs=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=300
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/queue_%(process_num)s.log
stderr_logfile=/var/www/storage/logs/queue_%(process_num)s_error.log
